version: '3'
services:

  # nginx:
  #   image: nginx:latest
  #   depends_on:
  #     - webserver
  #     - mongodb
  #     - redis
  #     - frontend
  #   volumes:
  #     - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./certbot/www:/var/www/certbot/:ro
  #     - ./certbot/conf/:/etc/nginx/ssl/:ro
  #   ports:
  #     - 80:80
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  # redis:
  #   image: redis:latest
  #   # expose:
  #   #   - 6379
  #   ports:
  #     - 6379:6379
  mongodb:
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="nest"
    ports:
      - 27017:27017
    # expose:
    #   - 27017
  # frontend:
  #   build:
  #     context: ./magnify-frontend
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   # ports:
  #   #   - 3000:3000
  #   expose:
  #     - 3000
  # webserver:
  #   build:
  #     context: ./magnify-backend
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   # environment:
  #   #   - NEST_ENV=prod
  #   #   - DB_URL=mongodb
  #   depends_on:
  #     - redis
  #     # - mongodb
  #   ports:
  #     - 3000:3000
  #   expose:
  #     - 3000
  # peerserver:
  #   build:
  #     context: ./peerServer
  #     dockerfile: Dockerfile
  #   restart: on-failure
  #   expose:
  #     - 5000
